In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv("employee_data.csv")
print("Initial shape:", df.shape)
print(df.head())

# 1. Standardize column names
df.columns = (df.columns
                .str.strip()
                .str.lower()
                .str.replace(" ", "_")
                .str.replace(r"[()]", "", regex=True))
print("\nColumns after rename:", df.columns.tolist())

# 2. Check missing values
print("\nMissing values:\n", df.isnull().sum())

# Example handling: Fill missing gender with "Unknown"
if "gender" in df.columns:
    df["gender"] = df["gender"].astype(str).str.strip().str.lower()
    df["gender"] = df["gender"].replace({"m":"male", "f":"female"})
    df["gender"].fillna("unknown", inplace=True)

# Example handling: Drop rows with missing salary
if "salary" in df.columns:
    df["salary"] = pd.to_numeric(df["salary"], errors="coerce")
    df = df.dropna(subset=["salary"])

# 3. Remove duplicate employees
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]
print(f"\nRemoved {before - after} duplicate rows.")

# 4. Convert data types
if "emp_id" in df.columns:
    df["emp_id"] = pd.to_numeric(df["emp_id"], errors="coerce").astype("Int64")
if "hire_date" in df.columns:
    df["hire_date"] = pd.to_datetime(df["hire_date"], errors="coerce")

print("\nData types:\n", df.dtypes)

# 5. Save cleaned file
df.to_csv("employee_data_cleaned.csv", index=False)
print("\nCleaned file saved as employee_data_cleaned.csv")

Initial shape: (3000, 26)
   EmpID FirstName LastName  StartDate ExitDate                    Title  \
0   3427     Uriah  Bridges  20-Sep-19      NaN  Production Technician I
1   3428     Paula    Small  11-Feb-23      NaN  Production Technician I
2   3429    Edward     Buck  10-Dec-18      NaN       Area Sales Manager
3   3430   Michael  Riordan  21-Jun-21      NaN       Area Sales Manager
4   3431   Jasmine    Onque  29-Jun-19      NaN       Area Sales Manager

        Supervisor                        ADEmail BusinessUnit EmployeeStatus  \
0     Peter Oneill    uriah.bridges@bilearner.com         CCDR         Active
1  Renee Mccormick      paula.small@bilearner.com           EW         Active
2   Crystal Walker      edward.buck@bilearner.com           PL         Active
3   Rebekah Wright  michael.riordan@bilearner.com         CCDR         Active
4        Jason Kim    jasmine.onque@bilearner.com          TNS         Active

   ...              Division         DOB State JobFunctionDescription  \
0  ...  Finance & Accounting  07-10-1969    MA             Accounting
1  ...                Aerial  30-08-1965    MA                  Labor
2  ...         General - Sga  06-10-1991    MA              Assistant
3  ...  Finance & Accounting  04-04-1998    ND                  Clerk
4  ...         General - Con  29-08-1969    FL                Laborer

  GenderCode LocationCode  RaceDesc MaritalDesc Performance Score  \
0     Female        34904     White     Widowed       Fully Meets
1       Male         6593  Hispanic     Widowed       Fully Meets
2       Male         2330  Hispanic     Widowed       Fully Meets
3       Male        58782     Other      Single       Fully Meets
4     Female        33174     Other     Married       Fully Meets

  Current Employee Rating
0                       4
1                       3
2                       4
3                       2
4                       3

[5 rows x 26 columns]

Columns after rename: ['empid', 'firstname', 'lastname', 'startdate', 'exitdate', 'title', 'supervisor', 'ademail', 'businessunit', 'employeestatus', 'employeetype', 'payzone', 'employeeclassificationtype', 'terminationtype', 'terminationdescription', 'departmenttype', 'division', 'dob', 'state', 'jobfunctiondescription', 'gendercode', 'locationcode', 'racedesc', 'maritaldesc', 'performance_score', 'current_employee_rating']

Missing values:
 empid                            0
firstname                        0
lastname                         0
startdate                        0
exitdate                      1467
title                            0
supervisor                       0
ademail                          0
businessunit                     0
employeestatus                   0
employeetype                     0
payzone                          0
employeeclassificationtype       0
terminationtype                  0
terminationdescription        1467
departmenttype                   0
division                         0
dob                              0
state                            0
jobfunctiondescription           0
gendercode                       0
locationcode                     0
racedesc                         0
maritaldesc                      0
performance_score                0
current_employee_rating          0
dtype: int64

Removed 0 duplicate rows.

Data types:
 empid                          int64
firstname                     object
lastname                      object
startdate                     object
exitdate                      object
title                         object
supervisor                    object
ademail                       object
businessunit                  object
employeestatus                object
employeetype                  object
payzone                       object
employeeclassificationtype    object
terminationtype               object
terminationdescription        object
departmenttype                object
division                      object
dob                           object
state                         object
jobfunctiondescription        object
gendercode                    object
locationcode                   int64
racedesc                      object
maritaldesc                   object
performance_score             object
current_employee_rating        int64
dtype: object

Cleaned file saved as employee_data_cleaned.csv